# Generated by Django 3.2 on 2022-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=250)),
                ('message', models.TextField(max_length=1200)),
            ],
        ),
    ]
