# Generated by Django 3.2 on 2022-10-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alcohol_content',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
